import Board from "./Board";
import Bishop from "./pieces/Bishop";
import Queen from "./pieces/Queen";
import Rook from "./pieces/Rook";

const board = new Board("rnb1kbnr/pppp1ppp/8/4Q3/4q3/8/PPPP1PPP/RNB1KBNR");
board.loadPieces();
board.displayInConsole();
// console.table(board.darkCoverage.size);
// console.table(board.lightCoverage.size);
// const pawn = board.getPiece(1, 4);
// const knight = board.getPiece(7, 1);
// console.table(knight?.defaultMoves);
// const e = board.getPiece(6, 1);
// const rook = board.getPiece(3, 3);
// console.table(bishop?.legalMoves);
// board.movePiece({ rank: 2, file: 4 }, pawn);
// console.table(board.darkCoverage.size);
// console.table(board.lightCoverage.size);
// board.lightLegalMoves.forEach((e) => console.table(e));
// const bishop = board.getPiece(0, 5);
// console.table(bishop?.legalMoves);
// board.displayInConsole();
// board.movePiece({ rank: 4, file: 1 }, e);
// console.table(rook?.legalMoves);
// // board.movePiece({ rank: 3, file: 5 }, knight);
// board.displayInConsole();
// // console.table(bishop?.defaultMoves);
// // board.fen = "rnbqkbnr/pppp1ppp/8/8/8/8/PPPPPPPP/RNBQKBNR";
// board.displayInConsole();

// console.table(board.pieces, ["type", "shade", "pos", "legalMoves"]);
// const king = board.getKing("light");
const king = board.darkKing;
const darkQ = board.getPiece(3, 4);
const lightQ = board.getPiece(4, 4);
board.movePiece({ rank: 5, file: 3 }, board.getPiece(6, 3));
console.table(lightQ?.threatenedBy);
console.table(lightQ?.threatens);
console.table(board.getPiece(5, 3)?.threatenedBy);
board.displayInConsole();

// console.table(lightQ?.threatens);
// console.table(lightQ?.threatenedBy);
// console.table(board.getPiece(0, 5)?.legalMoves);
// console.log("King");
// console.table(king?.legalMoves);
// console.table(king?.threatenedBy);
// console.log("Queen");
// console.table(lightQ?.threatenedBy);
// console.table(lightQ?.threatens);
// console.table(darkQ?.threatenedBy);
// console.table(darkQ?.threatens);
// board.movePiece({ rank: 3, file: 0 }, darkQ);
// board.movePiece({ rank: 3, file: 4 }, darkQ);
board.displayInConsole();
// console.log("King");
// console.table(king?.threatenedBy);
// console.table(king?.threatens);
// console.log("Queen");
// console.table(lightQ?.threatens);
// console.table(lightQ?.threatenedBy);
// console.table(darkQ?.threatenedBy);
// console.table(darkQ?.threatens);
