import Board from "./Board";
import Bishop from "./pieces/Bishop";
import Queen from "./pieces/Queen";
import Rook from "./pieces/Rook";

// const board = new Board("rnbqkbnr/pppppppp/8/3P4/8/8/PPP1PPPP/RNBQKBNR");
const board = new Board("8/8/8/8/2qPK3/8/8/8");
board.loadPieces();
const P = board.getPiece(3, 3);
board.displayInConsole();
console.table(P?.legalMoves);
console.table(board.lightKing);
// console.table(P?.legalMoves);
// console.table(P?.defaultMoves);
// const p = board.getPiece(6, 4);
// board.movePiece({ rank: 4, file: 4 }, p);
// board.displayInConsole();
// console.table(P?.legalMoves);
// console.table(P?.defaultMoves);
// board.movePiece({ rank: 5, file: 4 }, P);
// board.displayInConsole();
// console.table(P);
// console.table(P?.myKingIsUnderCheck);
// console.table(board.lightKing?.isUnderCheck);
